# Generated by Django 5.2.10 on 2026-01-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('prompt', models.TextField(blank=True, help_text='场景提示词：该二级功能（场景）的提示词', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_list', to='Generate_testcases.featurelevel1')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, help_text='可选：会话级别的提示词（会覆盖场景提示词）', null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_sessions', to='Generate_testcases.featurelevel2')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField()),
                ('raw_text', models.TextField()),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(db_index=True, default=False)),
                ('regen_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regen_from_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regen_children', to='Generate_testcases.generationitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Generate_testcases.generationsession')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_batch_id', models.CharField(db_index=True, help_text='保存批次ID，格式：level2_{id}_timestamp', max_length=64)),
                ('idx', models.PositiveSmallIntegerField(help_text='在该批次中的序号')),
                ('text', models.TextField(help_text='测试用例内容')),
                ('version_title', models.CharField(blank=True, help_text='版本名称/备注', max_length=256, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('delivered', '已交付')], db_index=True, default='confirmed', help_text='用例状态', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_gen_item', models.ForeignKey(blank=True, help_text='来源生成项，用于追溯', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Generate_testcases.generationitem')),
                ('from_session', models.ForeignKey(blank=True, help_text='来源会话，用于追溯', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Generate_testcases.generationsession')),
                ('level2', models.ForeignKey(help_text='所属场景', on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='Generate_testcases.featurelevel2')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lang', models.CharField(default='zh', max_length=16)),
                ('source', models.CharField(default='import', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='Generate_testcases.featurelevel2')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationSeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveSmallIntegerField(default=5, help_text='该种子要生成的用例数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_configs', to='Generate_testcases.generationsession')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_configs', to='Generate_testcases.testcaseseed')),
            ],
        ),
        migrations.AddField(
            model_name='generationitem',
            name='seed',
            field=models.ForeignKey(blank=True, help_text='该生成项来自哪个种子', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='Generate_testcases.testcaseseed'),
        ),
        migrations.AddIndex(
            model_name='featurelevel2',
            index=models.Index(fields=['level1', 'name'], name='Generate_te_level1__b103e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featurelevel2',
            unique_together={('level1', 'name')},
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['level2', 'created_at'], name='Generate_te_level2__2a8adb_idx'),
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['status', 'created_at'], name='Generate_te_status_1b4fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcaseitem',
            index=models.Index(fields=['level2', 'created_at'], name='Generate_te_level2__0b7e01_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcaseitem',
            index=models.Index(fields=['saved_batch_id', 'idx'], name='Generate_te_saved_b_57a782_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcaseitem',
            index=models.Index(fields=['status', 'created_at'], name='Generate_te_status_2b8b87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedcaseitem',
            unique_together={('saved_batch_id', 'idx')},
        ),
        migrations.AddIndex(
            model_name='testcaseseed',
            index=models.Index(fields=['level2', 'lang'], name='Generate_te_level2__b09457_idx'),
        ),
        migrations.AddIndex(
            model_name='generationseedconfig',
            index=models.Index(fields=['session', 'seed'], name='Generate_te_session_6b70da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generationseedconfig',
            unique_together={('session', 'seed')},
        ),
        migrations.AddIndex(
            model_name='generationitem',
            index=models.Index(fields=['session', 'idx'], name='Generate_te_session_89d5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='generationitem',
            index=models.Index(fields=['is_edited'], name='Generate_te_is_edit_4e7ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='generationitem',
            index=models.Index(fields=['seed'], name='Generate_te_seed_id_878124_idx'),
        ),
    ]
